import { useLocation } from "wouter";
import { ArrowLeft, FileText } from "lucide-react";

const LAST_UPDATED = "11 May 2026";
const COMPANY = "VARAH Group";
const PRODUCT = "ARYA";
const EMAIL = "support@aryaai.in";
const WEBSITE = "aryaai.in";

export default function TermsAndConditions() {
  const [, setLocation] = useLocation();

  return (
    <div className="min-h-screen bg-white dark:bg-slate-950 text-gray-900 dark:text-white">
      <div className="max-w-3xl mx-auto px-4 py-10">
        <button
          onClick={() => setLocation("/")}
          className="flex items-center gap-2 text-sm text-muted-foreground hover:text-gray-900 dark:hover:text-white mb-8 transition-colors"
        >
          <ArrowLeft className="w-4 h-4" /> Back to ARYA
        </button>

        <div className="flex items-center gap-3 mb-2">
          <div className="w-9 h-9 rounded-xl bg-amber-100 dark:bg-amber-900/30 flex items-center justify-center">
            <FileText className="w-5 h-5 text-amber-600 dark:text-amber-400" />
          </div>
          <h1 className="text-2xl font-bold">Terms &amp; Conditions</h1>
        </div>
        <p className="text-sm text-muted-foreground mb-10">
          Last updated: {LAST_UPDATED} &nbsp;·&nbsp; Please read these carefully before using ARYA
        </p>

        <div className="prose prose-gray dark:prose-invert max-w-none space-y-8 text-sm leading-relaxed">

          <section>
            <h2 className="text-base font-semibold text-gray-900 dark:text-white mb-3">1. Acceptance of Terms</h2>
            <p className="text-muted-foreground">
              By accessing or using {PRODUCT} at <strong className="text-gray-900 dark:text-white">{WEBSITE}</strong> (the "Service"),
              you agree to be bound by these Terms &amp; Conditions ("Terms"). If you do not agree, you may not use the Service.
              These Terms constitute a legally binding agreement between you and <strong className="text-gray-900 dark:text-white">{COMPANY}</strong> ("we", "us", "our").
            </p>
            <p className="text-muted-foreground mt-2">
              These Terms are governed by the laws of <strong className="text-gray-900 dark:text-white">India</strong>, including
              the Information Technology Act, 2000 and applicable rules thereunder.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 dark:text-white mb-3">2. The Service</h2>
            <p className="text-muted-foreground">
              ARYA is a personal AI assistant designed to help you think clearly, set goals, reflect daily, and grow
              personally and professionally. The Service includes conversational AI, voice interaction, goal management,
              memory, mood check-ins, voice notes, and daily/weekly insights.
            </p>
            <p className="text-muted-foreground mt-2">
              ARYA's responses are generated by artificial intelligence and are intended for personal guidance and reflection.
              They do <strong className="text-gray-900 dark:text-white">not</strong> constitute professional medical, legal, financial,
              or psychological advice. Do not rely solely on ARYA for decisions that require qualified professional input.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 dark:text-white mb-3">3. Accounts &amp; Eligibility</h2>
            <ul className="list-disc list-inside text-muted-foreground space-y-1.5 ml-1">
              <li>You must be at least <strong className="text-gray-800 dark:text-gray-300">13 years old</strong> to use ARYA</li>
              <li>You are responsible for maintaining the confidentiality of your account credentials</li>
              <li>You are responsible for all activity that occurs under your account</li>
              <li>You must provide accurate and complete information when creating an account</li>
              <li>One person may not maintain more than one account without our prior written consent</li>
              <li>We reserve the right to suspend or terminate accounts that violate these Terms</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 dark:text-white mb-3">4. Acceptable Use</h2>
            <p className="text-muted-foreground mb-2">You agree not to use ARYA to:</p>
            <ul className="list-disc list-inside text-muted-foreground space-y-1.5 ml-1">
              <li>Generate, distribute, or store content that is illegal, harmful, threatening, or abusive</li>
              <li>Attempt to extract, reverse-engineer, or replicate ARYA's underlying AI models or systems</li>
              <li>Circumvent usage limits, rate limits, or access controls</li>
              <li>Harass, impersonate, or harm other users or third parties</li>
              <li>Use automated scripts or bots to interact with the Service without our permission</li>
              <li>Violate any applicable Indian or international laws or regulations</li>
              <li>Upload or transmit malicious code, viruses, or harmful content</li>
            </ul>
            <p className="text-muted-foreground mt-3">
              We reserve the right to suspend or terminate your access immediately and without notice for violations of this section.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 dark:text-white mb-3">5. Subscription Plans &amp; Payments</h2>

            <div className="space-y-4 text-muted-foreground">
              <div>
                <p className="font-medium text-gray-800 dark:text-gray-200 mb-1">5.1 Plans</p>
                <p>
                  ARYA offers a free tier and two paid subscription plans: <strong className="text-gray-800 dark:text-gray-300">Core (₹349/month)</strong> and <strong className="text-gray-800 dark:text-gray-300">Pro (₹549/month)</strong>.
                  Plan features and limits are as described on the pricing page at the time of subscription and may be updated with 30 days' notice.
                </p>
              </div>
              <div>
                <p className="font-medium text-gray-800 dark:text-gray-200 mb-1">5.2 Billing &amp; Auto-Renewal</p>
                <p>
                  Paid plans are billed on a <strong className="text-gray-800 dark:text-gray-300">monthly recurring basis</strong> via Razorpay.
                  By subscribing, you authorise Razorpay to automatically charge your payment method on each renewal date.
                  Subscriptions auto-renew unless cancelled at least 24 hours before the renewal date.
                </p>
              </div>
              <div>
                <p className="font-medium text-gray-800 dark:text-gray-200 mb-1">5.3 Taxes</p>
                <p>
                  All prices are exclusive of GST. Applicable GST will be added at checkout as required by Indian law.
                </p>
              </div>
              <div>
                <p className="font-medium text-gray-800 dark:text-gray-200 mb-1">5.4 Cancellation</p>
                <p>
                  You may cancel your subscription at any time from your account menu. Upon cancellation:
                </p>
                <ul className="list-disc list-inside mt-1.5 ml-3 space-y-1">
                  <li>Your subscription remains active until the end of the current billing period</li>
                  <li>You will not be charged for subsequent billing periods</li>
                  <li>No partial-month refunds are issued upon cancellation</li>
                  <li>Your account reverts to the Free plan at the end of the billing period</li>
                </ul>
              </div>
              <div>
                <p className="font-medium text-gray-800 dark:text-gray-200 mb-1">5.5 Refunds</p>
                <p>
                  We offer refunds in the following situations only:
                </p>
                <ul className="list-disc list-inside mt-1.5 ml-3 space-y-1">
                  <li>A technical error on our part caused a duplicate charge</li>
                  <li>The Service was unavailable for more than 72 consecutive hours due to our fault</li>
                  <li>You are a first-time subscriber and request a refund within <strong className="text-gray-800 dark:text-gray-300">7 days</strong> of your first charge</li>
                </ul>
                <p className="mt-2">
                  Refund requests must be submitted to <a href={`mailto:${EMAIL}`} className="text-emerald-600 dark:text-emerald-400 hover:underline">{EMAIL}</a>.
                  Approved refunds are processed within 5–7 business days to your original payment method.
                </p>
              </div>
              <div>
                <p className="font-medium text-gray-800 dark:text-gray-200 mb-1">5.6 Plan Changes</p>
                <p>
                  We reserve the right to modify pricing with 30 days' advance notice. Existing subscribers will retain
                  their current price for their active subscription period.
                </p>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 dark:text-white mb-3">6. Your Content</h2>
            <p className="text-muted-foreground">
              You retain ownership of all content you provide to ARYA — your messages, voice notes, goals, and personal information.
              By using ARYA, you grant us a limited, non-exclusive licence to process and store your content solely for the purpose
              of providing the Service to you. We do not use your content to train AI models or share it with third parties
              except as described in our Privacy Policy.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 dark:text-white mb-3">6A. Optional Personal Profile Data</h2>
            <p className="text-muted-foreground mb-3">
              ARYA offers an optional <strong className="text-gray-800 dark:text-gray-300">My Profile</strong> feature that allows you to
              share personal details to improve the personalisation of your experience. Completing your profile is entirely voluntary —
              ARYA functions without it.
            </p>
            <p className="text-muted-foreground mb-2">The optional profile fields include:</p>
            <ul className="list-disc list-inside text-muted-foreground space-y-1.5 ml-1 mb-3">
              <li><strong className="text-gray-800 dark:text-gray-300">Age</strong> — to tailor advice and context appropriately</li>
              <li><strong className="text-gray-800 dark:text-gray-300">City / Location</strong> — to provide locally relevant suggestions</li>
              <li><strong className="text-gray-800 dark:text-gray-300">Occupation</strong> — to contextualise career and work-related guidance</li>
              <li><strong className="text-gray-800 dark:text-gray-300">Life stage</strong> (e.g. student, professional, parent) — to frame advice appropriately</li>
              <li><strong className="text-gray-800 dark:text-gray-300">Personal life situation</strong> (e.g. single, married) — for context-aware responses</li>
              <li><strong className="text-gray-800 dark:text-gray-300">Working style</strong> (e.g. early bird, night owl) — to personalise scheduling and productivity advice</li>
              <li><strong className="text-gray-800 dark:text-gray-300">Interests &amp; hobbies</strong> — to make conversations more relevant and engaging</li>
              <li><strong className="text-gray-800 dark:text-gray-300">Current challenges</strong> — to focus ARYA's support on what matters most to you right now</li>
            </ul>
            <p className="text-muted-foreground">
              This data is stored securely in your account, used exclusively to personalise your ARYA experience, and is never sold,
              shared with third parties, or used to train AI models. You may update or delete any profile information at any time from
              the <strong className="text-gray-800 dark:text-gray-300">My Profile</strong> section in your account menu.
            </p>
            <p className="text-muted-foreground mt-2">
              No government-issued identifiers, financial information, or sensitive personal data (as defined under the Digital
              Personal Data Protection Act, 2023) are collected through the profile feature.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 dark:text-white mb-3">7. Intellectual Property</h2>
            <p className="text-muted-foreground">
              The ARYA platform, including its design, code, branding, and AI-generated content, is the intellectual property
              of {COMPANY}. You may not copy, reproduce, distribute, or create derivative works from any part of the Service
              without our express written permission. "ARYA" and "{COMPANY}" are trademarks of {COMPANY}.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 dark:text-white mb-3">8. Disclaimers &amp; Limitation of Liability</h2>
            <div className="space-y-3 text-muted-foreground">
              <p>
                The Service is provided "as is" and "as available" without warranties of any kind, either express or implied,
                including but not limited to warranties of merchantability, fitness for a particular purpose, or non-infringement.
              </p>
              <p>
                <strong className="text-gray-800 dark:text-gray-300">ARYA is an AI assistant, not a professional.</strong> Responses
                are not a substitute for qualified medical, legal, financial, psychological, or other professional advice.
                Never disregard professional advice based on what ARYA says.
              </p>
              <p>
                To the maximum extent permitted by applicable Indian law, {COMPANY} shall not be liable for any indirect,
                incidental, special, consequential, or punitive damages arising from your use of or inability to use the Service,
                even if we have been advised of the possibility of such damages.
              </p>
              <p>
                Our total liability to you for any claim arising out of or relating to the Service shall not exceed the amount
                you paid to us in the <strong className="text-gray-800 dark:text-gray-300">three (3) months</strong> preceding the claim.
              </p>
            </div>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 dark:text-white mb-3">9. Service Availability</h2>
            <p className="text-muted-foreground">
              We strive for high availability but do not guarantee uninterrupted access to the Service. We may perform
              scheduled or emergency maintenance, which may result in temporary downtime. We will endeavour to provide
              advance notice for scheduled maintenance. We are not liable for any losses arising from service interruptions.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 dark:text-white mb-3">10. Termination</h2>
            <p className="text-muted-foreground">
              Either party may terminate this agreement at any time. You may terminate by deleting your account and
              ceasing use of the Service. We may terminate or suspend your access immediately, without prior notice,
              if you breach these Terms, violate applicable laws, or if we discontinue the Service.
              Upon termination, your right to use ARYA ceases immediately.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 dark:text-white mb-3">11. Governing Law &amp; Dispute Resolution</h2>
            <p className="text-muted-foreground">
              These Terms are governed by and construed in accordance with the laws of <strong className="text-gray-900 dark:text-white">India</strong>.
              Any disputes arising under these Terms shall be subject to the exclusive jurisdiction of the courts of
              <strong className="text-gray-900 dark:text-white"> India</strong>.
            </p>
            <p className="text-muted-foreground mt-2">
              We encourage you to contact us first at <a href={`mailto:${EMAIL}`} className="text-emerald-600 dark:text-emerald-400 hover:underline">{EMAIL}</a> to resolve
              any dispute amicably before initiating formal legal proceedings.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 dark:text-white mb-3">12. Changes to These Terms</h2>
            <p className="text-muted-foreground">
              We may update these Terms at any time. We will provide at least <strong className="text-gray-900 dark:text-white">14 days' notice</strong> before
              material changes take effect by posting a notice in the ARYA interface or by email. Continued use of the
              Service after the effective date of changes constitutes your acceptance of the revised Terms.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 dark:text-white mb-3">13. Contact</h2>
            <div className="bg-gray-50 dark:bg-slate-800 rounded-xl p-4 text-muted-foreground text-sm">
              <p className="font-medium text-gray-900 dark:text-white">{COMPANY}</p>
              <p>Support: <a href={`mailto:${EMAIL}`} className="text-emerald-600 dark:text-emerald-400 hover:underline">{EMAIL}</a></p>
              <p>Privacy: <a href="mailto:privacy@aryaai.in" className="text-emerald-600 dark:text-emerald-400 hover:underline">privacy@aryaai.in</a></p>
              <p>Website: <a href={`https://${WEBSITE}`} className="text-emerald-600 dark:text-emerald-400 hover:underline">{WEBSITE}</a></p>
            </div>
          </section>

        </div>

        <div className="mt-12 pt-8 border-t border-gray-100 dark:border-slate-800 text-center">
          <p className="text-xs text-muted-foreground">
            © {new Date().getFullYear()} {COMPANY}. All rights reserved. &nbsp;·&nbsp;
            <button onClick={() => setLocation("/privacy")} className="text-emerald-600 dark:text-emerald-400 hover:underline">Privacy Policy</button>
          </p>
        </div>
      </div>
    </div>
  );
}
